include: package:very_good_analysis/analysis_options.3.1.0.yaml
linter:
  rules:
    public_member_api_docs: false
    sort_pub_dependencies: false
    directives_ordering: false
    non_constant_identifier_names: false
    cascade_invocations: false
    comment_references: false
    depend_on_referenced_packages: false
    lines_longer_than_80_chars: false
    always_use_package_imports: false
analyzer:
  exclude:
    - '**/*.g.dart'
    - '**/*.config.dart'
