name: best_practice_template
description: Flutter best practices
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: 3.3.3

dependencies:
  bloc: ^8.1.0
  dio: ^4.0.6
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.5.4
  freezed: ^2.1.0+1
  get_it: ^7.2.0
  injectable: ^1.5.3
  intl: ^0.17.0
  json_annotation: ^4.7.0
  retrofit: ^3.3.1
  shimmer: ^2.0.0

dev_dependencies:
  build_runner: ^2.2.1
  bloc_test: ^9.1.0
  flutter_test:
    sdk: flutter
  injectable_generator: ^1.5.4
  retrofit_generator: ^4.2.0
  mocktail: ^0.3.0
  very_good_analysis: ^3.1.0
  json_serializable: ^6.4.1

flutter:
  uses-material-design: true
  generate: true
